<<<<<<< HEAD
=======
# Example YOLO training configuration
>>>>>>> 82a355e (restructuring)
### Configuration for yolo training script

# Setup for new Model
setup:
  yolo_base_model: yolo11s.yaml
<<<<<<< HEAD
  model_name: Screw_Detection_Model
  version: 1.0
  dataset: igmr_dataset_v2

# Parameters that define model training
training_params:
  epochs: 100
  batch_size: 16
=======
  model_name: Model_Name
  version: 1.0
  dataset: Dataset_Name

# Parameters that define model training
training_params:
  epochs: 300
  batch_size: 16
<<<<<<<< HEAD:Training/config/example_config.yaml
>>>>>>> 82a355e (restructuring)
  learning_rate: 0.001
  optimizer: AdamW
  img_size: 640
  multi_scale: true
  weight_decay: 0.0005
  seed: 42
<<<<<<< HEAD

# Parameters related to device used for training
runtime_settings:
  device: 0   # Devide for Training (0~GPU, None~CPU)
  workers: 0  # Multiprocessing (0 for Windows/ 4,8,16 else)
  amp: true  # Automatic Mixed Precision (TRUE ~ faster Training / FALSE ~ more stabil)
=======
========
  learning_rate: 0.005
  optimizer: AdamW
  img_size: 640           # Multiple of 32!
  multi_scale: true
  weight_decay: 0.0005
  seed: 333
>>>>>>>> 82a355e (restructuring):Configs/Training_configs/example_train_config.yaml

# Parameters related to device used for training
runtime_settings:
  device: 0   # Devide for Training (0~GPU, None~CPU) -> correct pytorch needs to be installed for gpu usage
  workers: 0  # Multiprocessing (0 for Windows/ 4,8,16 else)
  amp: true   # Automatic Mixed Precision (TRUE ~ faster Training / FALSE ~ more stabil)
>>>>>>> 82a355e (restructuring)

# (Optional) parameters to specify which augmentations yolo performes
augmentation_config:
  augmentation: True
  flipud: ~
  fliplr: ~
  mosaic: ~
  mixup: ~
  hsv_h: ~
  hsv_s: ~
  hsv_v: ~
<<<<<<< HEAD

# Hydra-specific settings
hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: .hydra
=======
>>>>>>> 82a355e (restructuring)
