setup:
  yolo_base_model: yolo26s.pt
  model_name: Universal_screw_detection
  version: 3.6
  dataset: igmr_universal_dataset_v3
training_params:
  target: 
    precision: 0.0
    recall: 0.6
    map50: 0.0
    map50_95: 0.4
  epochs: 800
  batch_size: -1
  learning_rate: 0.003
  optimizer: AdamW
  img_size: 1280
  multi_scale: false
  weight_decay: 1.8e-06
  seed: 653713
runtime_settings:
  device: 0
  workers: 8
  amp: true
augmentation_config:
  augmentation: true
  flipud: 0.2
  fliplr: 0.5
  mosaic: 0.2
  mixup: 0.1
  hsv_h: 0.01
  hsv_s: 0.15
  hsv_v: 0.15