# YOLO training configuration for Torx fine-tuning.

setup:
  yolo_base_model:
    experiment_group: Universal_screw_detection
    experiment_name: 3.4
    weights: best.pt

  experiment_group: Aubac_torx_detection
  experiment_name: 3.0

dataset:
  family: igmr_torx_finetune_dataset
  name: v3

experiment_series:
  enable: false

training_params:
  trainability_policy: backbone_frozen

  target:
    precision: 0.0
    recall: 0.6
    map50: 0.0
    map50_95: 0.4

  epochs: 300
  batch_size: 2
  learning_rate: 5e-5
  optimizer: AdamW
  img_size: 1280
  multi_scale: false
  weight_decay: 1e-6
  seed: 5648

runtime_settings:
  device: 0
  workers: 8
  amp: true

augmentation_config:
  augmentation: true
  flipud: 0.3
  fliplr: 0.5
  mosaic: 0.3
  mixup: 0.1
  hsv_h: 0.02
  hsv_s: 0.2
  hsv_v: 0.2
