setup:
  yolo_base_model: yolo26s.pt
  trainability_policy: full
  model_name: Finetuning_study
  version: 0.0
  dataset:
    family: finetuning_study
    name: mock_battery_step_test
training_params:
  target:
    precision: 0.0
    recall: 0.6
    map50: 0.0
    map50_95: 0.4
  epochs: 1000
  batch_size: 2
  learning_rate: 0.0005
  optimizer: AdamW
  img_size: 1280
  multi_scale: false
  weight_decay: 0.0001
  seed: 124542
runtime_settings:
  device: 0
  workers: 8
  amp: true
augmentation_config:
  augmentation: true
  flipud: 0.3
  fliplr: 0.5
  mosaic: 0.1
  mixup: 0.0
  hsv_h: 0.01
  hsv_s: 0.15
  hsv_v: 0.15
